services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
    command: ["3000", "localhost:8080"]
    depends_on:
      - db

  frontend:
    build:
      context: .
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/ngnix.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  db:
    image: postgres
    container_name: DataBase
    restart: unless-stopped
    environment:
      POSTGRES_USER: marius
      POSTGRES_PASSWORD: caracaca123
      POSTGRES_DB: CaraData
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
