services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db  # Override DB_HOST to use the service name instead of localhost
      - ALLOW_ORIGIN=localhost:8080  # Make sure this is explicitly set
    command: ["run", "--allow-net","--allow-ffi", "--allow-write", "--allow-env", "--allow-read", "--unstable-ffi", "--no-lock", "back_server.ts", "3000", "localhost:8080"]
    depends_on:
      - db
      - db-init  # Add dependency on db-init service
    volumes:
      - ./backend/cards_images:/app/cards_images  # Mount card images only, not the source code
      - ./backend/convertIMG.ts:/app/convertIMG.ts  # Mount the convertIMG.ts file

  # New service for database initialization
  db-init:
    build:
      context: ./backend
    restart: "no"
    networks:
      - app-network
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    volumes:
      - ./backend/cards_images:/app/cards_images
    depends_on:
      - db
    command: ["run", "--allow-net", "--allow-read", "--allow-env", "--unstable-ffi", "--no-lock", "insert_cards.ts"]

  frontend:
    build:
      context: .
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/ngnix.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # Database service
  db:
    image: postgres:14
    container_name: DataBase
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

# Networks section
networks:
  app-network:
    driver: bridge

# Volumes section
volumes:
  postgres_data:
